const STR = {
  ABSENT: "absent",
  ACCEPTED: "ACCEPTED",
  ACCESS_DENIED: "Access Denied!",
  ACCOUNTANT: "accountant",
  ACTIVE: "active",
  ADMIN: "admin",
  APPROVED: "APPROVED",
  ASSIGNED: "assigned",
  ASSIGNMENT: "ASSIGNMENT",
  AFTERNOON_SHIFT: "afternoon_shift",
  ALTERNATE: "alternate",
  ATTENDANCE_BUS: "attendance-bus",
  ATTENDANCE_CLASS: "attendance-class",
  A_ENTRY: "aEntry",
  A_EXIT: "aExit",
  BUS: "bus",
  BUS_FEE: "BUS FEE",
  BUS_STAFF: "bus_staff",
  CASH: "CASH",
  CHECKED: "checked",
  CHEQUE_OR_DD: "CHEQUE_OR_DD",
  CLASSWORK: "CLASSWORK",
  CONTINUOUS: "continuous",
  CONDUCTOR: "conductor",
  CUSTOM: "custom",
  CUSTOMVALIDATION: "CustomValidation",
  CUR_AYEAR_NOT_SET:
    "Current academic year not set, please set the current academic year!",
  CREDIT: "credit",
  DAILY: "daily",
  DB_BACKUP_TIME_LAST: "DB_BACKUP_TIME_LAST",
  DRIVER: "driver",
  DEBIT: "debit",
  EARLY: "early",
  EMAIL_QUEUE: "email_queue",
  ENTRY: "entry",
  EVENING_SHIFT: "evening shift",
  EVENT_FEE_PAID_NOTIFY: "EVENT_FEE_PAID_NOTIFY",
  EVENT_REGISTRATION_FEE_PAID_NOTIFY: "EVENT_REGISTRATION_FEE_PAID_NOTIFY",
  EXIT: "exit",
  EXPENSE: "expense",
  EXEMPTED: "EXEMPTED",
  FEE: "fee",
  FEE_COLLECTION: "FEE_COLLECTION",
  FEE_RECEIPT_SEQUENCE: "FEE_RECEIPT_SEQUENCE",
  FEMALE: "f",
  FIELD_IS_INVALID: "is invalid!",
  FIELD_IS_INVALID_AT_IDX: "%F% is invalid at row: %I%",
  FIELD_MISSING: "%F% is missing!",
  FIELD_IS_REQ: "is required!",
  FIELD_IS_REQ_: "%F% is required!",
  FIELD_IS_REQ_AT_IDX: "%F% is required at row: %I%",
  FLEXI_SHIFT: "flexi_shift",
  FIXED: "fixed",
  FLEXIBLE: "flexible",
  FUNC_MISSING_ARGUMENT: "Function is missing argument: %F%",
  FUND_TRANSFER_IN: "FUND_TRANSFER_IN",
  FUND_TRANSFER_OUT: "FUND_TRANSFER_OUT",
  GRADED: "GRADED",
  HOMEWORK: "HOMEWORK",
  HOLIDAY_HOMEWORK: "HOLIDAY HOMEWORK",
  INCOME: "income",
  INCOMPLETE: "INCOMPLETE",
  INVALID_CREDENTIALS: "Invalid Credentials!",
  INVALID_ADMNO: "Invalid Admission Number!",
  INACTIVE: "inactive",
  ISSUED: "issued",
  JUNIOR: "junior",
  LATE: "late",
  LATE_SUBMISSION: "LATE SUBMISSION",
  LIBRARIAN: "librarian",
  MALE: "m",
  MARKS_MUST_BE_WHOLE_NO: "Marks must be a whole number!",
  MISC: "misc",
  MONTHLY: "monthly",
  MORNING_SHIFT: "morning_shift",
  MULTI: "multi",
  M_ENTRY: "mEntry",
  M_EXIT: "mExit",
  NA: "na",
  NEEDS_REVISION: "NEEDS REVISION",
  NEW: "n",
  NIGHT_SHIFT: "night_shift",
  NO: "no",
  NOTICE: "notice",
  OLD: "o",
  ONE_TIME_FEES: "ONE_TIME_FEES",
  ONLINE: "ONLINE",
  OTHERS: "OTHERS",
  OTHERS_GENDER: "o",
  PAGE_LIMIT_REACHED: "Page limit reached!",
  PARENT: "parent",
  PARTIAL_FEES: "PARTIAL_FEES:",
  PENDING: "PENDING",
  POS_MACHINE: "POS_MACHINE",
  PRESENT: "present",
  PROJECT: "PROJECT",
  PUSH_QUEUE: "push_queue",
  RAZORPAY: "RAZORPAY",
  RECEPTIONIST: "receptionist",
  REGISTRATION_APPLICATION_YEAR: "REGISTRATION_APPLICATION_%Y%",
  REGISTRATION_PAYMENT: "REGISTRATION_PAYMENT",
  REJECTED: "REJECTED",
  RESOURSE_404: "%R% not found",
  RESOURSE_404_ID: "%R% not found: %ID%",
  RESUBMITTED: "RESUBMITTED",
  RETURNED: "returned",
  SCHOOL: "school",
  SENIOR: "senior",
  SINGLE: "single",
  STAFF: "staff",
  STUDENT: "student",
  SUPERADMIN: "superadmin",
  TEACHER: "teacher",
  TERM_FEES: "TERM_FEES:",
  TEST: "test",
  UNABLE_TO_DEL: "Unable to delete: %A% assigned to %B%!",
  UNASSIGNED: "unassigned",
  UNCHECKED: "unchecked",
  UNKNOWN: "unknown",
  UNDER_REVIEW: "UNDER REVIEW",
  URL_404: "URL not found!",
  VALUE_NOT_SUP: "'{VALUE}' is not supported!",
  VALUE_NOT_SUP_AT_IDX: "%V% is not supported at row: %I%",
  WEEKLY: "weekly",
  WHATSAPP_QUEUE: "whatsapp_queue",
  YES: "yes",
};

const FUNCTIONS = {
  getFieldIsInvalid: (field) => `${field} ` + STR.FIELD_IS_INVALID,
  getFieldIsInvalidAtIdx: (field, idx) =>
    STR.FIELD_IS_INVALID_AT_IDX.replace("%F%", field).replace("%I%", idx),
  getFieldMissing: (field) => STR.FIELD_MISSING.replace("%F%", field),
  getFieldIsReq: (field) => STR.FIELD_IS_REQ_.replace("%F%", field),
  getFieldIsReqAtIdx: (field, idx) =>
    STR.FIELD_IS_REQ_AT_IDX.replace("%F%", field).replace("%I%", idx),
  getFuncMissArg: (arg) => STR.FUNC_MISSING_ARGUMENT.replace("%F%", arg),
  getRegAppYear: (year) => STR.REGISTRATION_APPLICATION_YEAR.replace("%Y%", year),
  getResourse404: (resource) => STR.RESOURSE_404.replace("%R%", resource),
  getResourse404Id: (resource, id) =>
    STR.RESOURSE_404_ID.replace("%R%", resource).replace("%ID%", id),
  getUnableToDel: (a, b) => STR.UNABLE_TO_DEL.replace("%A%", a).replace("%B%", b),
  getValueNotSup: (val) => STR.VALUE_NOT_SUP.replace("{VALUE}", val),
  getValueNotSupAtIdx: (val, idx) =>
    STR.VALUE_NOT_SUP_AT_IDX.replace("%V%", val).replace("%I%", idx),
};

module.exports = UC = {
  ...STR,
  ...FUNCTIONS,
};
